// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZrauXkVZUJFvY03STucxz5FgCpXCxLqQ',
    appId: '1:289357692973:web:2920a17adb3e13099cb8a4',
    messagingSenderId: '289357692973',
    projectId: 'registrojornada-cd6fd',
    authDomain: 'registrojornada-cd6fd.firebaseapp.com',
    storageBucket: 'registrojornada-cd6fd.appspot.com',
    measurementId: 'G-8PHZCZ6ZZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF5l-VkzEc9A4PBMGXhLeH3fN2VFj-PsM',
    appId: '1:289357692973:android:f8841eda52fb286d9cb8a4',
    messagingSenderId: '289357692973',
    projectId: 'registrojornada-cd6fd',
    storageBucket: 'registrojornada-cd6fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvPB44gwKMrO7oTrpIFdI5xWI-x8jybi0',
    appId: '1:289357692973:ios:89b21d287dd564ad9cb8a4',
    messagingSenderId: '289357692973',
    projectId: 'registrojornada-cd6fd',
    storageBucket: 'registrojornada-cd6fd.appspot.com',
    iosClientId: '289357692973-bq1v2pn1db65buarakqo8fnpnvvcmb9b.apps.googleusercontent.com',
    iosBundleId: 'com.dam.registroJornada',
  );
}
